-- Creating tables for Final Project
CREATE TABLE acn (
	date VARCHAR(40) NOT NULL,
	Open VARCHAR(40) NOT NULL,
	High VARCHAR(40) NOT NULL,
	Low VARCHAR(40) NOT Null,
	Close VARCHAR(40) NOT NULL,
	Adj_Close VARCHAR(40) NOT NULL,
	Volume VARCHAR (40) NOT NULL
);

CREATE TABLE adbe (
	date VARCHAR(40) NOT NULL,
	Open VARCHAR(40) NOT NULL,
	High VARCHAR(40) NOT NULL,
	Low VARCHAR(40) NOT Null,
	Close VARCHAR(40) NOT NULL,
	Adj_Close VARCHAR(40) NOT NULL,
	Volume VARCHAR (40) NOT NULL
);

CREATE TABLE amd (
	date VARCHAR(40) NOT NULL,
	Open VARCHAR(40) NOT NULL,
	High VARCHAR(40) NOT NULL,
	Low VARCHAR(40) NOT Null,
	Close VARCHAR(40) NOT NULL,
	Adj_Close VARCHAR(40) NOT NULL,
	Volume VARCHAR (40) NOT NULL
);

CREATE TABLE crm (
	date VARCHAR(40) NOT NULL,
	Open VARCHAR(40) NOT NULL,
	High VARCHAR(40) NOT NULL,
	Low VARCHAR(40) NOT Null,
	Close VARCHAR(40) NOT NULL,
	Adj_Close VARCHAR(40) NOT NULL,
	Volume VARCHAR (40) NOT NULL
);

CREATE TABLE ibm (
	date VARCHAR(40) NOT NULL,
	Open VARCHAR(40) NOT NULL,
	High VARCHAR(40) NOT NULL,
	Low VARCHAR(40) NOT Null,
	Close VARCHAR(40) NOT NULL,
	Adj_Close VARCHAR(40) NOT NULL,
	Volume VARCHAR (40) NOT NULL
);

CREATE TABLE intc (
	date VARCHAR(40) NOT NULL,
	Open VARCHAR(40) NOT NULL,
	High VARCHAR(40) NOT NULL,
	Low VARCHAR(40) NOT Null,
	Close VARCHAR(40) NOT NULL,
	Adj_Close VARCHAR(40) NOT NULL,
	Volume VARCHAR (40) NOT NULL
);

CREATE TABLE intu (
	date VARCHAR(40) NOT NULL,
	Open VARCHAR(40) NOT NULL,
	High VARCHAR(40) NOT NULL,
	Low VARCHAR(40) NOT Null,
	Close VARCHAR(40) NOT NULL,
	Adj_Close VARCHAR(40) NOT NULL,
	Volume VARCHAR (40) NOT NULL
);

CREATE TABLE nflx (
	date VARCHAR(40) NOT NULL,
	Open VARCHAR(40) NOT NULL,
	High VARCHAR(40) NOT NULL,
	Low VARCHAR(40) NOT Null,
	Close VARCHAR(40) NOT NULL,
	Adj_Close VARCHAR(40) NOT NULL,
	Volume VARCHAR (40) NOT NULL
);

CREATE TABLE sony (
	date VARCHAR(40) NOT NULL,
	Open VARCHAR(40) NOT NULL,
	High VARCHAR(40) NOT NULL,
	Low VARCHAR(40) NOT Null,
	Close VARCHAR(40) NOT NULL,
	Adj_Close VARCHAR(40) NOT NULL,
	Volume VARCHAR (40) NOT NULL
);

CREATE TABLE txn (
	date VARCHAR(40) NOT NULL,
	Open VARCHAR(40) NOT NULL,
	High VARCHAR(40) NOT NULL,
	Low VARCHAR(40) NOT Null,
	Close VARCHAR(40) NOT NULL,
	Adj_Close VARCHAR(40) NOT NULL,
	Volume VARCHAR (40) NOT NULL
);